#!/bin/sh
version=$(grep AC_INIT configure.ac | grep -o "[0-9.]*")
./configure --prefix=$HOME/app/global-$version --with-exuberant-ctags=$(which ctags) || exit
make || exit
make install || exit

#Setup script
cat > setup_global_$version.source <<EOF
#Generated by build.sh
export PATH=\$PATH:~/app/global-$version/bin
export MANPATH=\$MANPATH:~/app/global-$version/share/man
export GTAGSCONF=$HOME/app/global-$version/share/gtags/gtags.conf
export GTAGSLABEL=ctags
EOF
cp setup_global_$version.source $HOME/bin

